### ISSUE TITLE
真机和模拟器中正常，previewer 中会提示 请在EntryAbility调用 ZRouter.init 初始化

### ISSUE THREAD

**Issue by llt22** [751496032/ZRouter#11]
`Device info:emulator
Build info:emulator 5.0.0.31(SP37DEVC00E31R4P11log)
Fingerprint:0b29e42a33d063485aa4644e081d4603fb47b0dcae5a28af903847ae1f6182c7
Module name:com.erlitech.woodenfish
Version:1.0.0
VersionCode:1000000
PreInstalled:No
Foreground:Yes
Pid:23152
Uid:20020036
Reason:Error
Error name:Error
Error message:请在EntryAbility调用 ZRouter.init 初始化
Stacktrace:
    at getRouterMgr (oh_modules/.ohpm/@hzw+zrouter@1.0.7/oh_modules/@hzw/zrouter/src/main/ets/api/Router.ets:42:15)
    at getNavStack (oh_modules/.ohpm/@hzw+zrouter@1.0.7/oh_modules/@hzw/zrouter/src/main/ets/api/Router.ets:57:12)
    at anonymous (products/phone/src/main/ets/pages/Index.ets:48:16)
    at updateFunc (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6740:1)
    at observeComponentCreation2 (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6781:1)
    at initialRender (products/phone/src/main/ets/pages/Index.ets:47:3)
    at initialRenderView (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6440:1)`
真假和模拟器中正常，previewer 中会提示 请在EntryAbility调用 ZRouter.init 初始化

**Comment by 751496032** [comment]
预览没有做适配
