### ISSUE TITLE
控制台 会输出错误

### ISSUE THREAD

**Issue by kbz066** [751496032/ZRouter#7]
![Uploading 58FDA8CC-FB4D-4ddb-8486-BD1DBF40DB36.png…]()

forEachChild error:  TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'NodeObject'
    |     property 'jsDoc' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'NodeObject'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Analyzer.resolveExpression (C:\Users\18211\.hvigor\project_caches\6b9846292fb429547cadbb1fc72ed916\workspace\node_modules\.pnpm\router-register-plugin@1.0.4\node_modules\router-register-plugin\src\router-register-plugin.ts:335:55)
    at Analyzer.resolveNode (C:\Users\18211\.hvigor\project_caches\6b9846292fb429547cadbb1fc72ed916\workspace\node_modules\.pnpm\router-register-plugin@1.0.4\node_modules\router-register-plugin\src\router-register-plugin.ts:314:22)
    at C:\Users\18211\.hvigor\project_caches\6b9846292fb429547cadbb1fc72ed916\workspace\node_modules\.pnpm\router-register-plugin@1.0.4\node_modules\router-register-plugin\src\router-register-plugin.ts:278:22
    at visitNodes (C:\Users\18211\.hvigor\project_caches\6b9846292fb429547cadbb1fc72ed916\workspace\node_modules\.pnpm\typescript@5.5.4\node_modules\typescript\lib\typescript.js:31751:22)
    at forEachChildInSourceFile (C:\Users\18211\.hvigor\project_caches\6b9846292fb429547cadbb1fc72ed916\workspace\node_modules\.pnpm\typescript@5.5.4\node_modules\typescript\lib\typescript.js:31964:12)
    at Object.forEachChild (C:\Users\18211\.hvigor\project_caches\6b9846292fb429547cadbb1fc72ed916\workspace\node_modules\.pnpm\typescript@5.5.4\node_modules\typescript\lib\typescript.js:32264:35)
    at Analyzer.start (C:\Users\18211\.hvigor\project_caches\6b9846292fb429547cadbb1fc72ed916\workspace\node_modules\.pnpm\router-register-plugin@1.0.4\node_modules\router-register-plugin\src\router-register-plugin.ts:275:30)
    at C:\Users\18211\.hvigor\project_caches\6b9846292fb429547cadbb1fc72ed916\workspace\node_modules\.pnpm\router-register-plugin@1.0.4\node_modules\router-register-plugin\src\router-register-plugin.ts:106:18
    at Array.forEach (<anonymous>)

**Comment by 751496032** [comment]
升级插件1.0.5
